### ISSUE TITLE
discord rpc id ne radi

### ISSUE THREAD

**Issue by MikMik1011** [ESX-Balkan/esxbalkan_mod#20]
discord rpc id dobijen uz mod ne radi, kada sam probao sa mojim id-jem radilo je lepo. 

esx-balkan plz fix.

**Comment by Tinky124** [comment]
hvala na prijavi @MikMik1011 bit ce u buducnosti fixano illi ako neko bude sredio jer mene mrzi da pravim sada novi id hahaha

**Comment by Tinky124** [comment]
Fixano
