### ISSUE TITLE
Garaza

### ISSUE THREAD

**Issue by LuxLuka** [ESX-Balkan/esxbalkan_mod#46]
Garaza ne radi

**Comment by synceye** [comment]
Što konkretno ne radi kod garaže? Ima li neki error i po mogućnosti slika server i client konzole?

**Comment by AltanBorancic** [comment]
> Što konkretno ne radi kod garaže? Ima li neki error i po mogućnosti slika server i client konzole?

Kada otvore garazu ovo im izbaci u F8
![IMAGE](https://user-images.githubusercontent.com/78441706/150794240-fcf91ea0-7e6e-48a9-b2a4-afd7f12c2ebe.png)

**Comment by LuxLuka** [comment]
i meni isto ovo

**Comment by Toni-d-e-v** [comment]
I meni isto garaze nerade

**Comment by Tinky124** [comment]
Fixano, skinite novi update, @LuxLuka, @Sefik17 @Toni-d-e-v
