### ISSUE TITLE
Nerade sefovi.

### ISSUE THREAD

**Issue by Toni-d-e-v** [ESX-Balkan/esxbalkan_mod#47]
Mozes staviti u sef ali kada kliknes makni iz sefa desi se ovo.
![image](https://user-images.githubusercontent.com/62844491/151671257-051bc1d1-65ec-4306-8328-32deb67220a4.png)

**Comment by Maatej10** [comment]
Samo u toj liniji promijeni label u name, npr ako je xItem.label promijeni
u xItem.name

sub, 29. jan 2022. 18:36 toni-dev ***@***.***> је написао/ла:

**Comment by Toni-d-e-v** [comment]
Hvala puno
